# Generated by Django 4.2.11 on 2024-04-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images_user',
            field=models.ImageField(blank=True, default='static/dist/img/credit/icons.png', null=True, upload_to='media/', verbose_name='تصویر کارشناس'),
        ),
    ]
